// Projects Data
const projectsData = [
    {
        name: "RaiseApp",
        description: "Plataforma para apoyar emprendimientos locales a través de tokenización de acciones.",
        url: "https://raise-app-rho.vercel.app",
        logo: "assets/logos/RaiseApp.png" // Path for logo image
    },
    {
        name: "Akala",
        description: "Plataforma de aprendizaje inclusiva que combina juegos de decisiones con situaciones de la vida real, diseñada para apoyar el desarrollo de habilidades lógicas en personas con discapacidad intelectual.",
        url: "https://www.figma.com/design/ojC9guT1z2HiQQ1OoMLxnv/Akala",
        logo: "assets/logos/Akala.jpg" // Path for logo image
    },
    {
        name: "Bragi",
        description: "Software web para conectar artistas con clientes, para que tengan la posibilidad de presentar sus servicios a la ciudad.",
        url: "https://www.figma.com/design/AmQPUAtlrZurNAtIAu6WhV/Bragi?node-id=0-1",
        logo: "assets/logos/Bragi.jpg" // Path for logo image
    },
    {
        name: "Cryptix",
        description: "Cryptix es una innovadora plataforma de venta de entradas basada en blockchain diseñada para revolucionar la forma en que las personas compran entradas para conciertos, eventos y más.",
        url: "https://cryptix-lemon.vercel.app",
        logo: "assets/logos/Cryptix.png" // Path for logo image
    },
    {
        name: "Drafty",
        description: "Inteligencia Artificial que genera planos de ingeniería a partir de una imagen.",
        url: "https://youtu.be/FD8ZfqGeZU0",
        logo: "assets/logos/Drafty.png" // Path for logo image
    },
    {
        name: "EtherWheels",
        description: "Revoluciona el uso compartido de vehículos a través de la integración de Web3 y Camp Network. Al aprovechar la tecnología blockchain, los usuarios pueden organizar viajes sin problemas, garantizando cálculos de tarifas justos y transacciones seguras. Dígale adiós a los problemas tradicionales del uso compartido del automóvil y adopte una alternativa más segura y descentralizada.",
        url: "https://youtu.be/n1eDyn68bm0",
        logo: "assets/logos/EtherWheels.jpg" // Path for logo image
    },
    {
        name: "BioNabu",
        description: "Our project, BioNabu, transforms NASA's vast collection of biological research into an accessible and intelligent knowledge platform. Many valuable studies about life sciences in space are currently scattered and difficult to explore. BioSpace Wiki solves this by using AI-powered summaries and interactive chat features that allow users to quickly understand, connect, and discuss findings from multiple NASA studies. Users can search for topics like \"plant growth in microgravity\" or \"cell adaptation in space\", select relevant articles, and instantly receive synthesized summaries, visual insights, and follow-up questions generated by the AI. Built with open NASA datasets, modern web technologies, and language models, the platform is designed to serve scientists, students, and enthusiasts alike. It aims to bridge the gap between data and discovery, making space bioscience research easier to understand and apply. Looking ahead, we envision integrating knowledge graphs and predictive analysis tools to help identify research gaps and guide future missions.",
        url: "https://youtu.be/KfM_jiR9zvE",
        logo: "assets/logos/BioNabu.png" // Path for logo image
    },
    {
        name: "GuardIA",
        description: "Inteligencia Artificial (IA) para identificar publicaciones fraudulentas en un marketplace, con el fin de prevenir estafas.",
        url: "#",
        logo: "assets/logos/guardia.png" // Path for logo image
    },
    {
        name: "Scrapper Judicial",
        description: "Bot de whatsapp para abogados que detecta las actuaciones de un caso y le notifica al usuario si se generaron nuevas actuaciones",
        url: "#",
        logo: "assets/logos/scrapper.png" // Path for logo image
    }
];

